// Dados iniciais do projeto. O Mestre pode importar estes registros pelo painel.
window.CRX_SEED = {
 common: [
  {name:"Lobissilva",level:3,porte:"Médio",porte_key:"medio",tipo:"Carnívoro",habitat:"Florestas",hp:40,energia:23,attrs:{forca:5,robustez:5,agilidade:7,instinto:6,afinidade:1,presenca:2},attacks:[["Mordida","Porte + Força"],["Garras","Porte + Força - 1"]],perks:{"Caça":3,"Rastreamento":2,"Esquiva":2,"Sobrevivência":1},specials:[],loot:["Presas","Couro","Garras","Carne"]},
  {name:"Pedracasco",level:5,porte:"Grande",porte_key:"grande",tipo:"Herbívoro",habitat:"Montanhas",hp:65,energia:19,attrs:{forca:7,robustez:10,agilidade:2,instinto:5,afinidade:2,presenca:3},attacks:[["Investida","Porte + Força"],["Chifrada","Porte + Força"]],perks:{"Casca Dura":3,"Resistência":2,"Suportar Dor":2,"Territorialismo":1},specials:[],loot:["Placas Rochosas","Chifre","Couro Espesso","Minério Preso ao Casco"]},
  {name:"Plumáurea",level:4,porte:"Pequeno",porte_key:"pequeno",tipo:"Onívoro",habitat:"Campos",hp:30,energia:30,attrs:{forca:2,robustez:3,agilidade:8,instinto:7,afinidade:3,presenca:3},attacks:[["Bicada","Porte + Força"],["Rajada de Penas","Porte + Afinidade"]],perks:{"Voo":3,"Esquiva":2,"Percepção":2,"Camuflagem":1},specials:[],loot:["Penas Luminosas","Bico","Ovos","Plumas"]},
  {name:"Lamalume",level:2,porte:"Médio",porte_key:"medio",tipo:"Onívoro",habitat:"Brejos",hp:35,energia:28,attrs:{forca:4,robustez:5,agilidade:4,instinto:5,afinidade:3,presenca:1},attacks:[["Mordida","Porte + Força"],["Cuspe Lodoso","Porte + Afinidade"]],perks:{"Camuflagem":2,"Natação":2,"Sobrevivência":2},specials:[],loot:["Muco Pegajoso","Pele Úmida","Glândula Viscosa"]},
  {name:"Escaravulcão",level:6,porte:"Pequeno",porte_key:"pequeno",tipo:"Inseto",habitat:"Vulcões",hp:42,energia:34,attrs:{forca:5,robustez:6,agilidade:5,instinto:5,afinidade:6,presenca:2},attacks:[["Pinças","Porte + Força"],["Bola de Magma","Porte + Afinidade"]],perks:{"Casca Dura":2,"Resistência ao Calor":3,"Escalada":2,"Sobrevivência":1},specials:[],loot:["Carapaça Vulcânica","Núcleo Magmático","Pinças","Cristal de Enxofre"]},
  {name:"Fruticervo",level:4,porte:"Médio",porte_key:"medio",tipo:"Herbívoro",habitat:"Bosques e Pomares",hp:48,energia:38,attrs:{forca:6,robustez:8,agilidade:6,instinto:9,afinidade:7,presenca:8},attacks:[["Chifrada Frutífera","Porte + Força"],["Investida","Porte + Força"],["Sementes Espirituais","Porte + Afinidade"]],perks:{"Fotossíntese":3,"Camuflagem":2,"Sobrevivência":3},specials:[],loot:["Fruto Espiritual","Casca Reforçada","Sementes Luminosas","Galho Ancião"]},
  {name:"Colosso Montanhoso",level:7,porte:"Colossal",porte_key:"colossal",tipo:"Mineral",habitat:"Cordilheiras",hp:110,energia:30,attrs:{forca:12,robustez:15,agilidade:1,instinto:5,afinidade:4,presenca:7},attacks:[["Pisoteio","Porte + Força"],["Punho de Pedra","Porte + Força"]],perks:{"Casca Dura":4,"Resistência":4,"Suportar Dor":3},specials:[],loot:["Fragmento de Pedra Viva","Minério Raro","Núcleo Mineral"]}
 ],
 players: [
  {name:"Erebus",species:"Lupus Australis",level:1,porte:"Médio",porte_key:"medio",tipo:"Player",habitat:"Florestas",category:"player",hp:30,energia:20,attrs:{forca:1,robustez:1,agilidade:1,instinto:2,afinidade:2,presenca:3},attacks:[["Mordida","Porte + Força"],["Garras","Porte + Força"]],perks:{"Mordida":1,"Suportar Dor":2,"Esquiva":1,"Caça":1,"Liderança":1},specials:["Camuflagem I"],loot:[],image_url:"erebus.png",owner_username:"rpg123"},
  {name:"Rudy",species:"Ragal",level:1,porte:"Grande",porte_key:"grande",tipo:"Player",habitat:"Florestas e montanhas",category:"player",hp:35,energia:10,attrs:{forca:2,robustez:2,agilidade:2,instinto:2,afinidade:0,presenca:2},attacks:[["Mordida","Porte + Força"],["Garras","Porte + Força"]],perks:{"Mordida":1,"Garras":1,"Resistência":1,"Regeneração":1,"Corrida":1,"Natação":1,"Caça":1,"Intimidação":1},specials:[],loot:[],image_url:"rudy.png",owner_username:"rpg456"},
  {name:"Plataus",species:"Guerreiro Valente",level:1,porte:"Médio",porte_key:"medio",tipo:"Player",habitat:"Variável",category:"player",hp:35,energia:10,attrs:{forca:3,robustez:2,agilidade:2,instinto:2,afinidade:0,presenca:1},attacks:[["Mordida","Porte + Força"],["Garras","Porte + Força"]],perks:{},specials:[],loot:[],image_url:"plataus.png",owner_username:"rpg456"}
 ]
};
